package HR;

public class Q4Q6 {
	
	--4번 문제

	SELECT e.LAST_NAME AS 사원이름 , d.DEPARTMENT_NAME AS 부서이름
	FROM EMPLOYEES e, LOCATIONS l,DEPARTMENTS d 
	WHERE l.CITY = 'Seattle'
	AND e.DEPARTMENT_ID = d.DEPARTMENT_ID 
	AND d.LOCATION_ID = l.LOCATION_ID
	GROUP BY e.LAST_NAME, d.DEPARTMENT_NAME, l.CITY 
	ORDER BY e.LAST_NAME;

	SELECT e2.LAST_NAME, EMPLOYEE_ID, l.CITY, e2.DEPARTMENT_ID, e2.MANAGER_ID 
	FROM EMPLOYEES e2, LOCATIONS l, DEPARTMENTS d 
	WHERE l.CITY = 'Seattle'
	AND e2.DEPARTMENT_ID = d.DEPARTMENT_ID 
	AND d.LOCATION_ID = l.LOCATION_ID ;

	SELECT CASE WHEN e.EMPLOYEE_ID = e.MANAGER_ID THEN e.LAST_NAME END 
	FROM DEPARTMENTS d, EMPLOYEES e ;

	SELECT 
	       E.E_NAME AS 사원이름, NVL(E.M_NAME, '<없음>')AS 매니저이름, D.DEPARTMENT_NAME AS 부서이름
	  FROM 
	      (
	       SELECT 
	              A.LAST_NAME AS E_NAME, B.LAST_NAME AS M_NAME, A.DEPARTMENT_ID 
	         FROM EMPLOYEES A 
	         LEFT JOIN EMPLOYEES B 
	           ON A.MANAGER_ID = B.EMPLOYEE_ID
	      ) E, DEPARTMENTS D, LOCATIONS L
	 WHERE L.CITY = 'Seattle' AND E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID
	 ORDER BY E.E_NAME ASC;  


	--5번 문제

	SELECT E.LAST_NAME AS 사원이름, A.*
	  FROM EMPLOYEES E, 
	      (
	      SELECT 
	             d.DEPARTMENT_NAME AS 부서이름, MIN(e.SALARY) AS 급여
	        FROM EMPLOYEES e, DEPARTMENTS d 
	       WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID 
	       GROUP BY d.DEPARTMENT_NAME
	       ORDER BY d.DEPARTMENT_NAME 
	      ) A 
	 WHERE E.SALARY = A.급여
	ORDER BY E.LAST_NAME ASC;

	--6번

	SELECT 
	       l.CITY , AVG(e.SALARY) , COUNT(*)
	  FROM EMPLOYEES e, LOCATIONS l, DEPARTMENTS d
	 WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID AND d.LOCATION_ID = l.LOCATION_ID
	 GROUP BY l.CITY
	HAVING COUNT(*) < 10
	 ORDER BY AVG(e.SALARY) ASC;
wk 

}
