package HR;

public class Q7Q8 {

	--7번 
	SELECT * 
	FROM 
	(SELECT j.JOB_TITLE AS 직책, AVG( e.SALARY) AS 평균급여 
	FROM JOBS j, EMPLOYEES e , DEPARTMENTS d 
	WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
	AND e.JOB_ID = j.JOB_ID 
	ORDER BY JOB_TITLE, AVG(e.SALARY)) 
	WHERE 평균급여 >= 2000;

	SELECT *
	FROM Dept30;

	CREATE OR REPLACE VIEW Dept30 AS 
	SELECT j.JOB_TITLE AS 직책, AVG(e.SALARY) AS 평균급여
	FROM EMPLOYEES e, JOBS j 
	WHERE e.JOB_ID = j.JOB_ID 
	HAVING AVG(e.SALARY) >= 2000
	GROUP BY j.JOB_TITLE;

	SELECT * 
	FROM Dept30;

	--8번
	SELECT e.EMPLOYEE_ID AS 사번, CONCAT(CONCAT(e.FIRST_NAME, ' '), e.LAST_NAME) AS 이름 
	FROM EMPLOYEES e, JOBS j, JOB_HISTORY jh 
	WHERE j.JOB_TITLE = 'Public Accountant' 
	AND j.JOB_ID = jh.JOB_ID 
	AND e.EMPLOYEE_ID = jh.EMPLOYEE_ID;
}
