package HR;

public class S06Q01 {

	--Section 06

	--01¹ø
	
	SELECT 
    e.FIRST_NAME, d.HIRE_DATE, e.M_NAME
FROM 
   (
    SELECT 
           A.FIRST_NAME AS FIRST_NAME, a.HIRE_DATE, B.FIRST_NAME AS M_NAME 
      FROM EMPLOYEES A 
      LEFT JOIN EMPLOYEES B 
        ON A.MANAGER_ID = B.EMPLOYEE_ID
   ) e, EMPLOYEES d
WHERE  EXTRACT(YEAR FROM d.HIRE_DATE) >= 1980 AND EXTRACT(YEAR FROM d.HIRE_DATE) <= 1989
AND d.EMPLOYEE_ID = e.EMPLOYEE_ID;
	
}
