package HR;

public class Sec03Q01Sec05Q01 {
	
	--03

	--4번

	SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY 
	FROM EMPLOYEES e, JOBS j 
	WHERE j.JOB_TITLE = 'Sales Representative'
	AND e.SALARY <= 10000
	AND j.JOB_ID = e.JOB_ID;

	SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY, j.JOB_TITLE 
	FROM EMPLOYEES e, JOBS j 
	WHERE j.JOB_TITLE = 'Sales Representative'
	AND e.JOB_ID = j.JOB_ID; 

	--Section 04

	--1번

	SELECT j.JOB_TITLE, SUM(e.SALARY) 
	FROM EMPLOYEES e, JOBS j
	WHERE e.JOB_ID = j.JOB_ID 
	HAVING SUM(e.SALARY) >30000
	GROUP BY j.JOB_TITLE ; 

	--2번

	SELECT e.EMPLOYEE_ID, e.FIRST_NAME, j.JOB_TITLE, d.DEPARTMENT_NAME 
	FROM EMPLOYEES e, JOBS j, LOCATIONS l,DEPARTMENTS d 
	WHERE l.CITY = 'Seattle'
	AND e.JOB_ID = j.JOB_ID 
	AND e.DEPARTMENT_ID = d.DEPARTMENT_ID
	AND d.LOCATION_ID = l.LOCATION_ID ;

	SELECT *
	FROM LOCATIONS l, DEPARTMENTS d 
	WHERE d.LOCATION_ID = l.LOCATION_ID;

	--Section 05

	--1번

	CREATE OR REPLACE VIEW Dept_view AS
	SELECT d.DEPARTMENT_NAME AS NAME, MIN(e.SALARY) AS MINSAL, 
	MAX(e.SALARY) AS MAXSAL, AVG(e.SALARY) AS AVGSAL 
	FROM EMPLOYEES e, DEPARTMENTS d 
	WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
	GROUP BY d.DEPARTMENT_NAME ;

	SELECT *
	FROM Dept_view;

}
