package HR;

public class Section07 {
	
	--Section 07

	--01번

	SELECT EXTRACT(MONTH FROM e.HIRE_DATE) || '월'AS 월
	FROM EMPLOYEES e, DEPARTMENTS d 
	GROUP BY EXTRACT(MONTH FROM e.HIRE_DATE)
	ORDER BY EXTRACT(MONTH FROM e.HIRE_DATE) ; 
	
	--02번
	SELECT d2.DEPARTMENT_NAME, e2.FIRST_NAME, A.max_sal
	FROM EMPLOYEES e2, DEPARTMENTS d2, 
			(SELect d.DEPARTMENT_NAME AS Dept_NAME, MAX(e.SALARY) AS max_sal 
	      	FROM EMPLOYEES e,DEPARTMENTS d 
			WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
			GROUP BY d.DEPARTMENT_NAME
			)  A
	WHERE e2.SALARY = A.max_sal
	AND d2.DEPARTMENT_NAME = A.Dept_NAME
	AND e2.DEPARTMENT_ID = d2.DEPARTMENT_ID ;

}
