package HR;

public class Section02Q0102 {

	--1¹ø

	SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, NVL(d.DEPARTMENT_NAME, '<NOT ASSIGNED>') 
	FROM EMPLOYEES e, DEPARTMENTS d 
	WHERE EXTRACT(YEAR FROM hire_date) = 1999
	AND e.DEPARTMENT_ID = d.DEPARTMENT_ID 
	GROUP BY e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, NVL(d.DEPARTMENT_NAME, '<NOT ASSIGNED>') ;

	SELECT FIRST_NAME,d.DEPARTMENT_NAME 
	FROM EMPLOYEES e ,DEPARTMENTS d 
	WHERE e.FIRST_NAME = 'Kimberely'
	GROUP BY e.FIRST_NAME, d.DEPARTMENT_NAME,d.DEPARTMENT_ID ;

	--2¹ø

	SELECT *
	FROM EMPLOYEES e;

	CREATE TABLE EMPLOYESS_MARKETING(
					EMPLOYEE_ID NUMBER(6,0),
					FIRST_NAME VARCHAR(20),
					LAST_NAME VARCHAR(25),
					EMAIL VARCHAR(25),
					PHONE_NUMBER VARCHAR(20),
					HIRE_DATE DATE,
					JOB_ID VARCHAR(10),
					SALARY NUMBER(8,2),
					COMMISION_PCT NUMBER(2,2),
					MANAGER_ID NUMBER(6,0),
					DEPARTMENT_ID NUMBER(4,0)
					);

	INSERT INTO EMPLOYESS_MARKETING(EMPOYE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISION_PCT,MANAGER_ID,DEPARTMENT_ID) VALUES(201,'Michael','hartstein',MARTSTE,515.123.5555)
	
}
