package HR;

public class Section09 {
	
	--Section 09

	--01번

	SELECT NVL(TO_CHAR(TRUNC( e.COMMISSION_PCT, 1)),'<커미션 없음>') AS COMMISSION, count(*)
	FROM EMPLOYEES e 
	GROUP BY NVL(TO_CHAR(TRUNC( e.COMMISSION_PCT, 1)),'<커미션 없음>')
	ORDER BY NVL(TO_CHAR(TRUNC( e.COMMISSION_PCT, 1)),'<커미션 없음>') DESC;

	--02번

	SELECT *
	FROM 
	(SELECT d.DEPARTMENT_NAME 부서명, e.FIRST_NAME 직원명, e.SALARY 급여, TO_CHAR(TRUNC( e.COMMISSION_PCT, 2)) 커미션
	FROM EMPLOYEES e, DEPARTMENTS d 
	WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
	ORDER BY e.COMMISSION_PCT DESC NULLS LAST, e.SALARY DESC)
	WHERE rownum <=4;

}
